spring:
  application:
    name: musinsa
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import:
      - application-datasource.yaml
      - application-jpa.yaml
  jackson:
    time-zone: Asia/Seoul

server:
  servlet:
    context-path: /api
  shutdown: graceful
  port: 8080
